[package]
name = "overhead-benchmark"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
maudit = { workspace = true }
itoa = "1.0"

[dev-dependencies]
divan = { version = "3.0.5", package = "codspeed-divan-compat" }

[[bench]]
name = "build"
harness = false
