[package]
name = "maudit-example-runtime-to-the-max"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.maudit]
intended_version = "0.6.2"

[dependencies]
maudit = { workspace = true }
