[dependencies.maud]
workspace = true

[dependencies.maudit]
workspace = true

[dependencies.oubli]
workspace = true

[package]
edition = "2021"
name = "oubli-example-basics"
publish = false
version = "0.1.1"
