[dependencies]
maud = "0.26.0"

[dependencies.maudit]
workspace = true

[dependencies.serde]
version = "1.0.216"

[package]
edition = "2021"
name = "maudit-example-blog"
publish = false
version = "0.1.1"

[package.metadata.maudit]
intended_version = "0.3.0"
