[package]
name = "maudit-example-blog"
version = "0.1.1"
edition = "2021"
publish = false

[package.metadata.maudit]
intended_version = "0.3.0"

[dependencies]
"maudit" = { version = "0.4.0" }
maud = "0.26.0"
serde = { version = "1.0.216" }