[package]
name = "maudit-example-markdown-components"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.maudit]
intended_version = "0.6.3"

[dependencies]
maudit = { workspace = true }
maud = "0.27.0"
serde = { workspace = true }
