[package]
name = "maudit-example-markdown-components"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.maudit]
intended_version = "0.2.0"

[dependencies]
maudit = { workspace = true }
maud = "0.26.0"
serde = { workspace = true }
