blank_issues_enabled: false
contact_links:
  - name: Any ideas or suggestions?
    url: https://github.com/bruits/maudit/discussions/categories/ideas
    about: Propose and discuss future improvements to Maudit (and Oubli).
  - name: Support or help needed? (GitHub)
    url: https://github.com/bruits/maudit/discussions/categories/q-a
    about: Ask questions and get help from the community.
  - name: Support or help needed? (Discord)
    url: https://maudit.org/chat/
    about: Ask questions and get help from the community.
