[package]
name = "maudit-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
maudit = { path = "../framework" }
maud = "0.26.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
