use rand::{rngs::ThreadRng, seq::IndexedRandom};

const ADJECTIVE: [&str; 35] = [
    "valiant",
    "gallant",
    "stalwart",
    "noble",
    "chivalrous",
    "fearless",
    "bold",
    "mighty",
    "regal",
    "venerable",
    "doughty",
    "heroic",
    "virtuous",
    "majestic",
    "ancient",
    "fabled",
    "valorous",
    "steadfast",
    "resolute",
    "forthright",
    "grumpy",
    "cantankerous",
    "cranky",
    "sullen",
    "pompous",
    "roguish",
    "wily",
    "somber",
    "haughty",
    "cunning",
    "dashing",
    "grim",
    "stern",
    "ardent",
    "jovial",
];
const TITLE: [&str; 35] = [
    "duke",
    "duchess",
    "marquess",
    "marchioness",
    "earl",
    "count",
    "countess",
    "baron",
    "baroness",
    "viscount",
    "viscountess",
    "lord",
    "lady",
    "knight",
    "baronet",
    "prince",
    "princess",
    "king",
    "queen",
    "landgrave",
    "palatine",
    "constable",
    "seneschal",
    "provost",
    "castellan",
    "ogre",
    "basilisk",
    "griffin",
    "chimera",
    "werewolf",
    "vampire",
    "dragon",
    "gorgon",
    "troll",
    "wyvern",
];
const NAME: [&str; 37] = [
    "amelia",
    "eleanor",
    "gwendolyn",
    "isolde",
    "matilda",
    "rosamund",
    "celestine",
    "genevieve",
    "cordelia",
    "ophelia",
    "edmund",
    "geoffrey",
    "oswald",
    "algernon",
    "reginald",
    "cedric",
    "theodore",
    "roderick",
    "finnian",
    "goulven",
    "lavinia",
    "rosalind",
    "bartholomew",
    "philip",
    "cornelius",
    "erika",
    "rosaline",
    "annabel",
    "mirabelle",
    "winifred",
    "vivienne",
    "leopold",
    "fitzroy",
    "walter",
    "roland",
    "giles",
    "aurelien",
];

pub fn generate_directory_name(rng: &mut ThreadRng) -> String {
    let title = TITLE.choose(rng).unwrap();
    let name = NAME.choose(rng).unwrap();
    let adjective = ADJECTIVE.choose(rng).unwrap();

    format!("{}-{}-{}", adjective, title, name)
}
