[package]
name = "maudit-example-kitchen-sink"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.maudit]
intended_version = "0.5.0"

[dependencies]
maudit = { workspace = true }
maud = "0.27.0"
