[package]
name = "maudit"
description = "Framework for generating static websites."
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
maud = "0.26.0"
maudit-macros = { path = "../macros", version = "0.1" }
log = { version = "0.4", features = ["kv"] }
env_logger = "0.11.5"
chrono = "0.4.39"
colored = "2.2.0"
rayon = "1.10.0"
rustc-hash = "2.1"
