[[bench]]
harness = false
name = "build"

[dependencies.maudit]
workspace = true

[dev-dependencies.divan]
package = "codspeed-divan-compat"
version = "3.0.5"

[package]
edition = "2021"
name = "md-benchmark"
publish = false
version = "0.1.1"
