[package]
name = "md-benchmark"
version = "0.1.1"
edition = "2021"
publish = false

[dependencies]
"maudit" = { version = "0.4.0" }

[dev-dependencies]
divan = { version = "3.0.5", package = "codspeed-divan-compat" }

[[bench]]
name = "build"
harness = false