[dependencies]
maud = "0.26.0"

[dependencies.maudit]
workspace = true

[package]
edition = "2021"
name = "maudit-example-basics"
publish = false
version = "0.1.1"

[package.metadata.maudit]
intended_version = "0.3.0"
