[package]
name = "maudit-example-basics"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.maudit]
intended_version = "0.3.0"

[dependencies]
maudit = { workspace = true }
maud = "0.26.0"
